version: "3"

services:
  uterm:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8999"
    restart: always
    environment:
      DATASOURCE_URL: "jdbc:mysql://db:3306/uterm"
      UTERM_DOMAIN: "localhost:8080"
    
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: fortest
      MYSQL_DATABASE: uterm
      MYSQL_USER: utermadmin
      MYSQL_PASSWORD: admin1234
