spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/uterm
    username: utermadmin
    password: admin1234

uterm:
  domain:
    name: "localhost"

server:
  error:
    whitelabel:
      enabled: true