spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/uterm
    username: utermadmin
    password: admin1234
  devtools:
    livereload:
      enalbes: true
  freemarker:
    cache: false

uterm:
  domain:
    name: "localhost"

server:
  error:
    whitelabel:
      enabled: false;