spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/uterm}
    username: utermadmin
    password: admin1234
  devtools:
    livereload:
      enalbes: true
  freemarker:
    cache: false

uterm:
  domain:
    name: ${UTERM_DOMAIN:localhost:8999}

server:
  port: ${SERVER_PORT:8999}
  error:
    whitelabel:
      enabled: false;